# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4feecf30573a5a8e79e576c9380c2edcee97a9861edbe2ea418d7c97d06a6f6590a0255abaeb6d4e067d14eb11320b837c0962a7263f5b40315a5dadae317f20

test:
  secret_key_base: ee3048a31d666314edd6a77a713666a6a441af90998ddc70b96a59175b769da75d1fda69d573665ddf7f89049d0c64bbecd056694efe2182f2d97dd2cdf16a9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
